pipeline {
    agent { label 'agent1' }

    stages {
        stage('Install dependencies') {
            steps {
                dir('fourth_lesson') {
                    sh '''
                        python3 -m venv .venv
                        . .venv/bin/activate
                        pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Parallel checks') {
            parallel {
                stage('Run tests') {
                    steps {
                        dir('fourth_lesson') {
                            sh '''
                                . .venv/bin/activate
                                pytest tests/
                            '''
                        }
                    }
                }

                stage('Run app check') {
                    steps {
                        dir('fourth_lesson') {
                            sh '''
                                . .venv/bin/activate
                                python app.py "hello_jenkins"
                            '''
                        }
                    }
                }
            }
        }

        stage('Build Docker image') {
            steps {
                dir('fourth_lesson') {
                    sh 'docker build -t text-analyzer .'
                }
            }
        }

        stage('Run Docker container') {
            steps {
                sh 'docker run --rm text-analyzer'
            }
        }
    }
}