pipeline {
    agent { label 'agent1' }

    stages {
        stage('Install dependencies') {
            steps {
                sh '''
                    python3 -m venv .venv
                    . .venv/bin/activate
                    pip install -r requirements.txt
                    pip install pytest
                '''
            }
        }

        stage('Parallel checks') {
            parallel {
                stage('Run tests') {
                    steps {
                        sh '''
                            . .venv/bin/activate
                            pytest
                        '''
                    }
                }

                stage('Run app check') {
                    steps {
                        sh '''
                            . .venv/bin/activate
                            python app.py "hello_jenkins"
                        '''
                    }
                }
            }
        }

        stage('Build Docker image') {
            steps {
                sh 'docker build -t text-analyzer .'
            }
        }

        stage('Run Docker container') {
            steps {
                sh 'docker run --rm text-analyzer'
            }
        }
    }
}