pipeline {
     agent { label 'agent1' }

    stages {
        stage('Install dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Parallel checks') {
            parallel {
                stage('Run tests') {
                    steps {
                        sh 'pytest'
                    }
                }

                stage('Run app check') {
                    steps {
                        sh 'python3 app.py "hello jenkins"'
                    }
                }
            }
        }

        stage('Build Docker image') {
            steps {
                sh 'docker build -t text-analyzer .'
            }
        }

        stage('Run Docker container') {
            steps {
                sh 'docker run --rm text-analyzer'
            }
        }
    }
}