pipeline {
    agent any

    parameters {
        choice(name: 'ENV', choices: ['dev', 'stage', 'prod'], description: 'Куда выполнять deploy')
        booleanParam(name: 'DO_DEPLOY', defaultValue: false, description: 'Выполнять Deploy stage?')
    }

    stages {

        stage('Build') {
            steps {
                dir('second_lesson') {
                    sh 'python3 --version'
                    sh 'python3 -m pip install --break-system-packages -r requirements.txt'
                }
            }
        }

        stage('Test') {
            steps {
                dir('second_lesson') {
                    sh 'pytest test_app.py'
                }
            }
        }

        stage('Deploy') {
            when {
                expression { params.DO_DEPLOY }
            }
            steps {
                dir('second_lesson') {
                    sh 'mkdir -p deploy'
                    sh 'echo "deployed to ${ENV} at $(date)" > deploy/deploy_${ENV}.txt'
                    sh 'ls -la deploy'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline finished SUCCESS'
        }
        failure {
            echo 'Pipeline finished FAILURE'
        }
        always {
            echo "ENV: ${params.ENV}, DO_DEPLOY: ${params.DO_DEPLOY}"
        }
    }
}